### ISSUE TITLE
I can't download the module

### ISSUE THREAD

**Issue by undesconocido** [ZWinther/lotr5e-module#11]
The module doesn't show up in the FoundryVTT in app Install System and when I try to use the `https://raw.githubusercontent.com/ZWinther/lotr5e-module/master/module.json` it fails

![image](https://github.com/ZWinther/lotr5e-module/assets/11449491/b8488ebd-194c-4e70-b6fb-37d876bb5951)

**Comment by ZWinther** [comment]
Hey there. So what's happening is that you're looking for the module under systems, but LOTR5E is a module for DnD5e, so you'll find it under modules.

However! The link in the readme was also outdated, so that's fixed now as well :)
