### ISSUE TITLE
Character Sheet - Avatar/Token accessibility bug?

### ISSUE THREAD

**Issue by rsimmerm** [ZWinther/lotr5e-module#12]
Hello,

I'm a new user to your module, but not Foundry.  

I'm using The Forge VTT hosting site.
Foundry v10 303 build.
D&D 5e 2.3.1
I am using 29 modules, but I don't think it's a module conflict.

I've set the Core and User configs and my players can't edit their avatar/prototype token or drag them to the map/scenes.  I can certainly do it myself as the GM, but it'd be nice if they could do it as well for one last thing for me to do.

**Comment by ZWinther** [comment]
Sorry for the late reply, but have you tried with only my module enabled, to see if the problem exists there?

I don't have the problem on my end at the very least.

Also, I don't believe that players can ever drag their own tokens to the map, unless they have special privileges.
