### ISSUE TITLE
Future enhancement-Additional item options?

### ISSUE THREAD

**Issue by rsimmerm** [ZWinther/lotr5e-module#13]
Any chance we can add vehicle/mount as an item selection?

Same goes for trade goods etc?

![image](https://github.com/ZWinther/lotr5e-module/assets/8026848/5ec19875-12e4-4995-bdef-1addcb4c2ad2)

**Comment by ZWinther** [comment]
Vehicles and Mounts are usually actors rather than items:
![image](https://github.com/ZWinther/lotr5e-module/assets/82144909/aa9eaf3e-7087-449d-8f20-d039995f1f65)

I haven't played in a while, but is Trade Goods a specific thing in the LOTR5E rules?
