### ISSUE TITLE
Can't install lotr5e - is the manifest URL working?

### ISSUE THREAD

**Issue by DM-BenC** [ZWinther/lotr5e-module#14]
If you put the manifest URL for this module into the field and try to install the module it throws an error. Is it currently working?

**Comment by ZWinther** [comment]
Just tried it a couple of times, and I can install it with no issues.

Make sure you install it as a module and not a system.

**Comment by DM-BenC** [comment]
Thanks Dan - you may have just solved the issue. Human error! Doh! 👍🤣

Sent from Samsung Mobile on O2
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
