### ISSUE TITLE
The little bugs of 2.4

### ISSUE THREAD

**Issue by Padhiver** [ZWinther/lotr5e-module#15]
Edit : All issue in this post with fixed when updating system translation ! o/

**Comment by Padhiver** [comment]
Also, in LOTR5e there is a new tool, "Pipe", if it's possible to add it?
![image](https://github.com/ZWinther/lotr5e-module/assets/80126915/b7d442ed-a890-4b7f-900f-dc4897775149)

**Comment by Padhiver** [comment]
In the Special Trait tab of character sheet, there is lot of DND5E ... etc : 

![image](https://github.com/ZWinther/lotr5e-module/assets/80126915/b354408e-0350-4bd6-a917-dd51edf5512e)

**Comment by ZWinther** [comment]
Thanks for gathering the bugs in one place. Work is incredibly busy at the moment, so it might be some time before I can fix them. I'll get around to it as fast as I can.

**Comment by Padhiver** [comment]
No worries, none of these bugs prevent you from playing, it's just visual. :) Thank you !

**Comment by Padhiver** [comment]
Got this error on a blank world with just the module : 

![image](https://github.com/ZWinther/lotr5e-module/assets/80126915/cb31e8cf-c7c2-42a8-b0ac-6a4322445275)

**Comment by Padhiver** [comment]
> Thanks for gathering the bugs in one place. Work is incredibly busy at the moment, so it might be some time before I can fix them. I'll get around to it as fast as I can.

Apparently many of these errors were due to the translation of the system, with the updates they have all disappeared ...! All that's left is to add the pipe as a tool. :D
