### ISSUE TITLE
DnD 5e - 3.0 Release

### ISSUE THREAD

**Issue by EddieEldridge** [ZWinther/lotr5e-module#17]
Hey Dan, absolutely love this module and am really enjoying using it in my games!

Are there any plans to update to accommodate the new 3.0 release of the 5e system with the new character sheet layout and whatnot?

![image](https://github.com/ZWinther/lotr5e-module/assets/22448079/d0fa2677-1754-41fe-8340-8ebae0b4e4cf)

Happy to donate to get this across the line, thank you so much again!

**Comment by ZWinther** [comment]
I hope to update the module soonish. Work and life stuff has been really
getting in the way for a while.

I might have time this weekend, but at the very least I'll try to get an
overview of how much work it's going to be and go from there :)

**Comment by TastyEmpire** [comment]
Hopefully it won't be a huge undertaking to update, but it does look like this 3.0 release made a lot of changes. Thanks for your hard work!

**Comment by ZWinther** [comment]
Working on it now. There's a lot of fairly simple stylesheet fixes, but some of the updates may require finding new workarounds to avoid messing things up for you guys.

I can't give a timeframe but I'll be hacking away at it whenever I have time :)

**Comment by ZWinther** [comment]
Finally got some breathing room and got to sit down and update the module. Please report any bugs if you find them :)

**Comment by EddieEldridge** [comment]
Thanks so much Dan, can't wait to try it out!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
