### ISSUE TITLE
Item sheets issue

### ISSUE THREAD

**Issue by cwlithgow** [ZWinther/lotr5e-module#18]
Looks like this module messes with the items sheets a bit. Trying to create an item (feature) with limited uses...without this module the drop down looks like this:
![image](https://github.com/ZWinther/lotr5e-module/assets/85030999/2bfd485a-299c-474d-9a74-55d1dbaf50e9)
 With the module enabled it looks like this:
![image](https://github.com/ZWinther/lotr5e-module/assets/85030999/fb6b866e-0444-4b2d-8e84-2294d39417a2)

If you click into the "blank" choices it appears to make a selection...but still missing choices in the new drop down:
![image](https://github.com/ZWinther/lotr5e-module/assets/85030999/91b52f46-ec3a-4175-82f7-046e5d598f9c)

These are the versions:
![image](https://github.com/ZWinther/lotr5e-module/assets/85030999/7707e8d0-f8c5-4798-b38b-5ffebbb18216)

Version 0.5.1 of this module.

D&D 3.1.2

Look forward to your thoughts!

**Comment by cwlithgow** [comment]
Turns out that the choices are actually still there in the menu...the text is just missing/invisible. You can still make the selection if you already know the order of the choices and things appear to work fine.

**Comment by ZWinther** [comment]
Should be fixed in the latest release. Apologies for the delay.

**Comment by cwlithgow** [comment]
I found another similar issue....Consumable items - consumable type drop down is blank:
![image](https://github.com/ZWinther/lotr5e-module/assets/85030999/181f53ac-4714-4521-85d4-d1e11b0f9fa9)
Should look like this one:
![Consumabletypes](https://github.com/ZWinther/lotr5e-module/assets/85030999/eb6cd036-07bb-4234-b077-3b9eca730e4d)
Thanks for your work as always!

**Comment by ZWinther** [comment]
Yeah it's almost certainly a similar bug and similar fix.

I'll see about getting an update out tomorrow.
