### ISSUE TITLE
Unable to edit items.

### ISSUE THREAD

**Issue by VincePayne42** [ZWinther/lotr5e-module#20]
With only this module enabled using the latest Dungeons & Dragons Fifth Edition game system, nobody logged into the game is able to edit any weapons. Disabling this module fixed the issue. Not sure what the issue is.

**Comment by ZWinther** [comment]
Just to be sure, when you say only this module, do mean LOTR5e and libWrapper?

**Comment by VincePayne42** [comment]
Sorry, to be more precise, LoTR5e and LibWrapper were enabled. We are also on the latest version of foundry.

**Comment by ZWinther** [comment]
I have an inkling about what it could be.
Can you check a few things for me?

- The version of the 5e system, this module and libWrapper.
- See if there are any errors in the developer console (press f12 when you've loaded into a world and hit ctrl+f5 to refresh.

**Comment by VincePayne42** [comment]
5e System 4.1.0, libwrapper 1.13.2.0, LoTR 5E 0.6.0. 

In the console, I see these errors

```
Error: An error occurred while rendering ItemSheet5e2 25. CONFIG.DND5E.itemProperties[k] is undefined
[Detected 1 package: system:dnd5e(4.1.0)]
    onError foundry.js:654
    onError#0 libWrapper-wrapper.js:188
    render foundry.js:5795
Caused by: TypeError: CONFIG.DND5E.itemProperties[k] is undefined
[Detected 1 package: system:dnd5e(4.1.0)]
    options sheet-v2-mixin.mjs:179
    reduce foundry-esm.js:4270
    getData sheet-v2-mixin.mjs:178
[foundry.js:655:30](https://dinguskhan.net/lotr/scripts/foundry.js)
Uncaught TypeError: Window.getComputedStyle: Argument 1 is not an object.
[Detected 1 package: system:dnd5e(4.1.0)]
    setPosition foundry.js:6347
    setPosition sheet-v2-mixin.mjs:230
    _onWindowResize foundry.js:10352
```

**Comment by ZWinther** [comment]
Ahh there was a new somewhat update for the 5e system just a few days after I updated the module, and it probably broke something.

I'll see if I can find some time to update it again tomorrow, and otherwise reverting to version 4.0.4 of 5e should work until I do.
