### ISSUE TITLE
Character Sheets Broken

### ISSUE THREAD

**Issue by pete284** [ZWinther/lotr5e-module#9]
Since the update of core D&D system to 2.2.1 (in Version 10) the Character sheets are broken. 

- It messes up the abilities on the front page
- Loses the new languages
- brings back the spellbook tab

See attached
![LOTR Character Sheets](https://github.com/ZWinther/lotr5e-module/assets/55640052/31c58dbd-7d26-43ab-9bb2-b33a227bb5fd)

**Comment by pete284** [comment]
Version 0.31 works fine now on Foundry V.11 and DnD V. 2.2.1. 

Version 0.3 on V.10 of foundry with DnD V. 2.2.1 still has the same problem, however I don't know if you can also maintain the old Foundry version now you have the new version. 

I am running both v.10 and v.11 on seperate machines waiting for all the modules to be v.11 compatible!!

**Comment by ZWinther** [comment]
I'll take a look at it after work, and see what I can do.

**Comment by ZWinther** [comment]
The new version is now available in v10. Can you check if it works properly there?

**Comment by pete284** [comment]
Yes everything fixed in V10 too, thank you for all the work.
